version: 0.2

env:
  variables:
    ENV: 'dev'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo installing dependencies...
      - npm install
  build:
    commands:
      - mv .platform/nginx/dev-nginx.conf .platform/nginx/nginx.conf && rm .platform/nginx/prod-nginx.conf
      - npm run build
      - export NODE_CONFIG_DIR=./dist/config
artifacts:
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
    - 'node_modules/**/*'
